In [3]:
import pandas as pd

dataFrame = pd.read_csv("https://raw.githubusercontent.com/zief0002/epsy-5261/main/data/countries.csv")

In [13]:
dataFrame.columns

Index(['country', 'region', 'population', 'area', 'gdp', 'life_expect',
       'birth_rate', 'fertility_rate', 'death_rate', 'infant_mortality'],
      dtype='str')

In [19]:
dataFrame[["country", "population"]]
dataFrame.iloc[10]["country"]

'Azerbaijan'

In [24]:
dataFrame.head()
dataFrame[dataFrame["area"] > 300000]

,country,region,population,area,gdp,life_expect,birth_rate,fertility_rate,death_rate,infant_mortality
0,Afghanistan,South Asia,38041754.0,652860.0,507.103432,64.833,31.802,61.3250,6.285,46.5
2,Algeria,Middle East & North Africa,43053054.0,2381741.0,3973.964072,76.880,23.583,9.5966,4.716,20.0
3,Angola,Sub-Saharan Africa,31825295.0,1246700.0,2790.726615,61.147,40.232,145.3900,7.981,50.2
5,Argentina,Latin America & Caribbean,44938712.0,2780400.0,9912.281809,76.667,16.833,62.3488,7.604,8.2
8,Australia,East Asia & Pacific,25365745.0,7741220.0,55057.204700,82.900,12.100,10.9366,6.700,3.1
...,...,...,...,...,...,...,...,...,...,...
189,"Venezuela, RB",Latin America & Caribbean,28515829.0,912050.0,NaN,72.064,17.566,84.6214,7.118,21.0
190,Vietnam,East Asia & Pacific,96462106.0,331230.0,2715.276036,75.400,16.454,27.3746,6.380,15.9
193,"Yemen, Rep.",Middle East & North Africa,29161922.0,527970.0,774.334490,66.125,29.873,57.9728,5.983,43.6
194,Zambia,Sub-Saharan Africa,17861030.0,752610.0,1305.063254,63.886,35.776,116.4976,6.321,42.4
195,Zimbabwe,Sub-Saharan Africa,14645468.0,390760.0,1463.985910,61.490,29.747,80.3622,7.773,38.4

In [29]:
dataFrame[dataFrame["country"] == "Poland"]
dataFrame[dataFrame["country"].str.startswith("P")]
dataFrame[~dataFrame["country"].str.startswith("P")] #~reverse operation

,country,region,population,area,gdp,life_expect,birth_rate,fertility_rate,death_rate,infant_mortality
0,Afghanistan,South Asia,38041754.0,652860.0,507.103432,64.833000,31.802,61.3250,6.285,46.5
1,Albania,Europe & Central Asia,2854191.0,28750.0,5353.244856,78.573000,11.620,19.5028,8.082,8.6
2,Algeria,Middle East & North Africa,43053054.0,2381741.0,3973.964072,76.880000,23.583,9.5966,4.716,20.0
3,Angola,Sub-Saharan Africa,31825295.0,1246700.0,2790.726615,61.147000,40.232,145.3900,7.981,50.2
4,Antigua and Barbuda,Latin America & Caribbean,97118.0,440.0,17112.821130,77.016000,15.107,40.8800,6.422,5.8
...,...,...,...,...,...,...,...,...,...,...
191,Virgin Islands (U.S.),Latin America & Caribbean,106669.0,350.0,NaN,79.668293,12.300,26.4094,8.200,NaN
192,West Bank and Gaza,Middle East & North Africa,4685306.0,6020.0,NaN,74.053000,28.717,50.9996,3.455,16.6
193,"Yemen, Rep.",Middle East & North Africa,29161922.0,527970.0,774.334490,66.125000,29.873,57.9728,5.983,43.6
194,Zambia,Sub-Saharan Africa,17861030.0,752610.0,1305.063254,63.886000,35.776,116.4976,6.321,42.4
195,Zimbabwe,Sub-Saharan Africa,14645468.0,390760.0,1463.985910,61.490000,29.747,80.3622,7.773,38.4

In [33]:
dataFrame.loc[dataFrame["country"] == "Poland"]
dataFrame["country"] = dataFrame["country"].str.upper()

In [34]:
dataFrame["country"]

0                AFGHANISTAN
1                    ALBANIA
2                    ALGERIA
3                     ANGOLA
4        ANTIGUA AND BARBUDA
               ...
191    VIRGIN ISLANDS (U.S.)
192       WEST BANK AND GAZA
193              YEMEN, REP.
194                   ZAMBIA
195                 ZIMBABWE
Name: country, Length: 196, dtype: str

In [36]:
dataFrame.dropna()
dataFrame.fillna({"population": 0}, inplace = True)

,country,region,population,area,gdp,life_expect,birth_rate,fertility_rate,death_rate,infant_mortality
0,AFGHANISTAN,South Asia,38041754.0,652860.0,507.103432,64.833000,31.802,61.3250,6.285,46.5
1,ALBANIA,Europe & Central Asia,2854191.0,28750.0,5353.244856,78.573000,11.620,19.5028,8.082,8.6
2,ALGERIA,Middle East & North Africa,43053054.0,2381741.0,3973.964072,76.880000,23.583,9.5966,4.716,20.0
3,ANGOLA,Sub-Saharan Africa,31825295.0,1246700.0,2790.726615,61.147000,40.232,145.3900,7.981,50.2
4,ANTIGUA AND BARBUDA,Latin America & Caribbean,97118.0,440.0,17112.821130,77.016000,15.107,40.8800,6.422,5.8
...,...,...,...,...,...,...,...,...,...,...
191,VIRGIN ISLANDS (U.S.),Latin America & Caribbean,106669.0,350.0,NaN,79.668293,12.300,26.4094,8.200,NaN
192,WEST BANK AND GAZA,Middle East & North Africa,4685306.0,6020.0,NaN,74.053000,28.717,50.9996,3.455,16.6
193,"YEMEN, REP.",Middle East & North Africa,29161922.0,527970.0,774.334490,66.125000,29.873,57.9728,5.983,43.6
194,ZAMBIA,Sub-Saharan Africa,17861030.0,752610.0,1305.063254,63.886000,35.776,116.4976,6.321,42.4
195,ZIMBABWE,Sub-Saharan Africa,14645468.0,390760.0,1463.985910,61.490000,29.747,80.3622,7.773,38.4